"""
OFNP — Signal Processing Pipeline
Open Facial Neuroprosthesis Project

Pipeline (Sec. 8.1 of documentation):
  1. Signal acquisition      → ADC samples from EMG electrodes
  2. Noise filtering         → bandpass + notch (50/60Hz power line)
  3. Feature extraction      → RMS, MAV, ZCR, envelope
  4. Expression detection    → threshold-based classifier (MVP)
  5. Trigger validation      → debounce, confidence gate
  6. Stimulation generation  → ramp profile (proportional to healthy-side intensity)
  7. Safety verification     → always last — cannot be bypassed
  8. Logging                 → all events recorded

PHASE: 0-2 (documentation, passive sensing, simulation)
NOTE:  Stimulation output (Step 6) operates in SIMULATION mode only.
       Hardware stimulation requires clinical validation per SAFETY_REQUIREMENTS.md
"""

from __future__ import annotations

import time
import math
import logging
import collections
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

import numpy as np

logger = logging.getLogger("ofnp.signal_processing")


# ─────────────────────────────────────────────────────────────────────────────
# Data Models
# ─────────────────────────────────────────────────────────────────────────────

class Expression(Enum):
    NEUTRAL            = "neutral"
    PARTIAL_SMILE      = "partial_smile"
    FULL_SMILE         = "full_smile"
    CHEEK_ACTIVATION   = "cheek_activation"
    UNKNOWN            = "unknown"


@dataclass
class RawSample:
    """Single ADC sample from one EMG channel."""
    timestamp: float           # Unix time in seconds
    channel_id: str            # e.g. "R_zyg" (right zygomaticus)
    voltage_uv: float          # microvolts
    impedance_kohm: float      # skin-electrode impedance


@dataclass
class FilteredSignal:
    """Output of noise filtering stage."""
    timestamp: float
    channel_id: str
    raw_uv: float
    filtered_uv: float
    is_artifact: bool          # True if signal is likely movement artifact
    snr_db: float              # Signal-to-noise ratio


@dataclass
class SignalFeatures:
    """
    Features extracted from a sliding window of filtered samples.
    Window: 200ms (configurable), hop: 50ms.
    """
    timestamp: float
    channel_id: str
    window_ms: float

    # Time-domain features
    rms_uv: float              # Root mean square amplitude
    mav_uv: float              # Mean absolute value
    zcr: float                 # Zero crossing rate (per second)
    peak_uv: float             # Peak amplitude in window
    envelope_uv: float         # Hilbert envelope mean

    # Derived
    baseline_uv: float         # Resting baseline (adaptive)
    activation_ratio: float    # rms / baseline — 1.0 = at rest, >2.0 = activated


@dataclass
class ExpressionEstimate:
    """Output of the expression detection stage."""
    timestamp: float
    expression: Expression
    confidence: float          # 0.0 – 1.0
    intensity: float           # 0.0 – 1.0 (used to scale stimulation)
    healthy_rms_uv: float      # Measured RMS on healthy side
    latency_ms: float          # Time from sample to estimate


@dataclass
class StimulationProfile:
    """
    Stimulation command generated by Step 6.
    In simulation mode: computed but NOT sent to hardware.
    In hardware mode: sent only after safety verification passes.
    """
    timestamp: float
    enabled: bool
    simulation_only: bool      # MUST be True in Phase 0-2
    target_muscle: str

    # Ramp profile (proportional to healthy-side intensity)
    ramp_up_ms: float          # Default: 50ms
    sustain_ms: float          # Duration of peak stimulation
    ramp_down_ms: float        # Default: 80ms
    peak_intensity_norm: float # 0.0 – 1.0 (scaled by clinician max)

    # Hardware parameters — set to None in simulation
    # MUST be validated by clinician before any hardware use
    current_ma: Optional[float] = None
    pulse_width_us: Optional[float] = None
    frequency_hz: Optional[float] = None

    def to_dict(self) -> dict:
        return {k: v for k, v in self.__dict__.items()}


# ─────────────────────────────────────────────────────────────────────────────
# Step 2: Noise Filtering
# ─────────────────────────────────────────────────────────────────────────────

class EMGFilter:
    """
    Real-time EMG filter chain:
      - 4th-order Butterworth bandpass (20–450 Hz for surface EMG)
      - 2nd-order notch at power-line frequency (50 or 60 Hz)
      - Artifact detection (impedance spike, saturation)

    Implementation: IIR biquad sections for real-time operation.
    In simulation: uses numpy for clarity; firmware uses fixed-point arithmetic.
    """

    SAMPLE_RATE_HZ  = 1000      # 1 kHz sampling
    BP_LOW_HZ       = 20.0      # Bandpass low cutoff
    BP_HIGH_HZ      = 450.0     # Bandpass high cutoff
    NOTCH_HZ        = 50.0      # Power line (50 Hz EU / 60 Hz US)
    SATURATION_UV   = 5000.0    # Above this = saturated signal (artifact)
    IMPEDANCE_MAX   = 50.0      # kΩ — above this = poor contact

    def __init__(self, power_line_hz: float = 50.0, sample_rate_hz: float = 1000.0):
        self.fs = sample_rate_hz
        self.notch_hz = power_line_hz

        # Simple exponential moving average for baseline estimation
        self._baseline: dict[str, float] = {}
        self._ema_alpha = 0.001          # Very slow update — baseline tracks DC drift

        # Ring buffer for SNR estimation (last 1 second)
        self._noise_floor: dict[str, collections.deque] = {}

        logger.info("[EMGFilter] Initialized: fs=%dHz bandpass=[%d-%dHz] notch=%dHz",
                    int(self.fs), int(self.BP_LOW_HZ), int(self.BP_HIGH_HZ), int(self.notch_hz))

    def filter(self, sample: RawSample) -> FilteredSignal:
        ch = sample.channel_id

        # Artifact detection first — no point filtering garbage
        is_artifact = (
            abs(sample.voltage_uv) > self.SATURATION_UV or
            sample.impedance_kohm > self.IMPEDANCE_MAX or
            sample.impedance_kohm < 0.1  # Disconnected or short
        )

        # Baseline update (only on clean samples)
        if ch not in self._baseline:
            self._baseline[ch] = sample.voltage_uv
        if not is_artifact:
            self._baseline[ch] = (
                self._ema_alpha * sample.voltage_uv +
                (1 - self._ema_alpha) * self._baseline[ch]
            )

        # Remove baseline (DC removal)
        dc_removed = sample.voltage_uv - self._baseline[ch]

        # In simulation: apply simple bandpass approximation via RMS
        # Production firmware uses proper IIR biquad cascade
        filtered = self._apply_bandpass_sim(dc_removed, ch)

        # Noise floor tracking
        if ch not in self._noise_floor:
            self._noise_floor[ch] = collections.deque(maxlen=1000)
        self._noise_floor[ch].append(abs(filtered))

        # SNR estimation
        noise = np.percentile(list(self._noise_floor[ch]), 10) if len(self._noise_floor[ch]) > 10 else 1.0
        signal_power = abs(filtered)
        snr = 20 * math.log10(max(signal_power, 1e-6) / max(noise, 1e-6))

        return FilteredSignal(
            timestamp=sample.timestamp,
            channel_id=ch,
            raw_uv=sample.voltage_uv,
            filtered_uv=filtered if not is_artifact else 0.0,
            is_artifact=is_artifact,
            snr_db=round(snr, 2),
        )

    def _apply_bandpass_sim(self, x: float, channel_id: str) -> float:
        """
        Simulation-mode bandpass: simple first-order highpass (removes <20Hz drift).
        Production: replace with scipy.signal.sosfilt biquad cascade.
        """
        # Simple highpass approximation (RC = 1/20Hz)
        alpha = 2 * math.pi * self.BP_LOW_HZ / self.fs
        key = f"_hp_{channel_id}"
        prev = getattr(self, key, 0.0)
        out = (1 - alpha) * (prev + x - getattr(self, f"_prev_x_{channel_id}", 0.0))
        setattr(self, key, out)
        setattr(self, f"_prev_x_{channel_id}", x)
        # Clamp to bandpass range
        return max(-self.BP_HIGH_HZ * 10, min(self.BP_HIGH_HZ * 10, out))


# ─────────────────────────────────────────────────────────────────────────────
# Step 3: Feature Extraction
# ─────────────────────────────────────────────────────────────────────────────

class FeatureExtractor:
    """
    Sliding window feature extraction from filtered EMG.
    Window: 200ms, hop: 50ms (overlap: 75%).
    """

    WINDOW_MS = 200
    HOP_MS    = 50

    def __init__(self, sample_rate_hz: float = 1000.0):
        self.fs = sample_rate_hz
        self._window_samples = int(self.WINDOW_MS * self.fs / 1000)
        self._hop_samples    = int(self.HOP_MS    * self.fs / 1000)
        self._buffers: dict[str, collections.deque] = {}
        self._sample_count: dict[str, int] = {}
        self._baselines: dict[str, collections.deque] = {}

    def push(self, signal: FilteredSignal) -> Optional[SignalFeatures]:
        """
        Push one filtered sample. Returns SignalFeatures when a window is complete.
        Returns None otherwise.
        """
        ch = signal.channel_id
        if ch not in self._buffers:
            self._buffers[ch] = collections.deque(maxlen=self._window_samples)
            self._sample_count[ch] = 0
            self._baselines[ch] = collections.deque(maxlen=self._window_samples * 10)

        # Skip artifacts
        if not signal.is_artifact:
            self._buffers[ch].append(signal.filtered_uv)
            self._baselines[ch].append(abs(signal.filtered_uv))

        self._sample_count[ch] += 1

        # Emit features every hop
        if self._sample_count[ch] % self._hop_samples == 0:
            if len(self._buffers[ch]) >= self._window_samples // 2:
                return self._compute_features(ch, signal.timestamp)

        return None

    def _compute_features(self, ch: str, ts: float) -> SignalFeatures:
        buf = np.array(list(self._buffers[ch]))
        baseline_samples = list(self._baselines[ch])
        baseline_uv = float(np.percentile(baseline_samples, 10)) if baseline_samples else 1.0
        baseline_uv = max(baseline_uv, 1.0)  # Minimum 1 µV to avoid division by zero

        rms  = float(np.sqrt(np.mean(buf ** 2)))
        mav  = float(np.mean(np.abs(buf)))
        zcr  = float(np.sum(np.diff(np.sign(buf)) != 0)) / (len(buf) / self.fs)
        peak = float(np.max(np.abs(buf)))

        # Hilbert envelope approximation via rectify + lowpass
        rect = np.abs(buf)
        alpha = 0.05
        env = np.zeros_like(rect)
        env[0] = rect[0]
        for i in range(1, len(rect)):
            env[i] = alpha * rect[i] + (1 - alpha) * env[i - 1]
        envelope = float(np.mean(env))

        return SignalFeatures(
            timestamp=ts,
            channel_id=ch,
            window_ms=self.WINDOW_MS,
            rms_uv=round(rms, 3),
            mav_uv=round(mav, 3),
            zcr=round(zcr, 2),
            peak_uv=round(peak, 3),
            envelope_uv=round(envelope, 3),
            baseline_uv=round(baseline_uv, 3),
            activation_ratio=round(rms / baseline_uv, 3),
        )


# ─────────────────────────────────────────────────────────────────────────────
# Step 4-5: Expression Detection + Trigger Validation
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class ExpressionThresholds:
    """
    Clinician-configurable thresholds for expression detection.
    These MUST be calibrated per patient in a supervised session.
    Default values are conservative placeholders only.
    """
    # Activation ratio thresholds (rms / baseline)
    partial_smile_min: float   = 2.5
    full_smile_min: float      = 4.5
    cheek_activation_min: float = 3.0

    # Confidence requirements
    min_confidence: float      = 0.70

    # Debounce: minimum number of consecutive positive windows
    debounce_windows: int      = 3    # 3 × 50ms hop = 150ms minimum sustained activation

    # False-trigger prevention
    max_activation_duration_s: float = 5.0   # Sustained >5s = likely artifact
    refractory_period_ms: float      = 500.0  # Minimum gap between triggers


class ExpressionDetector:
    """
    MVP threshold-based expression detector (Sec. 7.2: no deep learning initially).
    Detects: smile (partial/full), cheek activation.

    Accepts features from the healthy (sensing) hemiface channels.
    """

    def __init__(self, thresholds: Optional[ExpressionThresholds] = None):
        self.thresholds = thresholds or ExpressionThresholds()
        self._consecutive_hits: dict[Expression, int] = {e: 0 for e in Expression}
        self._last_trigger_time: dict[Expression, float] = {}
        self._activation_start: Optional[float] = None

    def detect(self, features: SignalFeatures) -> ExpressionEstimate:
        """Classify a feature window into an expression."""
        t0 = time.time()
        ratio = features.activation_ratio

        expression = Expression.NEUTRAL
        confidence = 1.0
        intensity  = 0.0

        # ── Classification ─────────────────────────────────────────────────
        if ratio >= self.thresholds.full_smile_min:
            expression = Expression.FULL_SMILE
            intensity  = min(1.0, (ratio - self.thresholds.full_smile_min) /
                            (self.thresholds.full_smile_min * 0.5) + 0.7)
            confidence = min(1.0, ratio / (self.thresholds.full_smile_min * 1.2))

        elif ratio >= self.thresholds.partial_smile_min:
            expression = Expression.PARTIAL_SMILE
            intensity  = min(0.7, (ratio - self.thresholds.partial_smile_min) /
                            (self.thresholds.full_smile_min - self.thresholds.partial_smile_min))
            confidence = min(1.0, ratio / self.thresholds.full_smile_min)

        elif ratio >= self.thresholds.cheek_activation_min:
            expression = Expression.CHEEK_ACTIVATION
            intensity  = min(0.8, ratio / (self.thresholds.cheek_activation_min * 1.5))
            confidence = 0.75

        # ── Debounce ───────────────────────────────────────────────────────
        if expression != Expression.NEUTRAL:
            self._consecutive_hits[expression] = self._consecutive_hits.get(expression, 0) + 1
            # Reset other counters
            for e in Expression:
                if e != expression:
                    self._consecutive_hits[e] = 0

            if self._consecutive_hits[expression] < self.thresholds.debounce_windows:
                expression = Expression.NEUTRAL   # Not confirmed yet
                confidence = 0.0
                intensity  = 0.0
        else:
            self._consecutive_hits = {e: 0 for e in Expression}
            if self._activation_start:
                self._activation_start = None

        # ── Refractory period ──────────────────────────────────────────────
        last_t = self._last_trigger_time.get(expression, 0.0)
        if (expression != Expression.NEUTRAL and
                (time.time() - last_t) * 1000 < self.thresholds.refractory_period_ms):
            expression = Expression.NEUTRAL
            confidence = 0.0
            intensity  = 0.0
        elif expression != Expression.NEUTRAL:
            self._last_trigger_time[expression] = time.time()

        latency_ms = (time.time() - t0) * 1000

        return ExpressionEstimate(
            timestamp=features.timestamp,
            expression=expression,
            confidence=round(confidence, 3),
            intensity=round(intensity, 3),
            healthy_rms_uv=features.rms_uv,
            latency_ms=round(latency_ms, 3),
        )


# ─────────────────────────────────────────────────────────────────────────────
# Step 6: Stimulation Profile Generator
# ─────────────────────────────────────────────────────────────────────────────

class StimulationProfileGenerator:
    """
    Converts an ExpressionEstimate to a StimulationProfile.

    ⚠ IMPORTANT: In Phase 0-2, simulation_only=True ALWAYS.
    Hardware stimulation requires:
      - Clinical validation of all parameters
      - Qualified biomedical engineer hardware review
      - Ethics committee approval for human subjects
      - Proper current limiting hardware
    """

    # Default ramp profile (ms) — clinician-adjustable
    DEFAULT_RAMP_UP_MS   = 50.0
    DEFAULT_SUSTAIN_MS   = 150.0
    DEFAULT_RAMP_DOWN_MS = 80.0

    MUSCLE_MAP = {
        Expression.FULL_SMILE:       "zygomaticus_major_L",
        Expression.PARTIAL_SMILE:    "zygomaticus_major_L",
        Expression.CHEEK_ACTIVATION: "risorius_L",
        Expression.NEUTRAL:          None,
        Expression.UNKNOWN:          None,
    }

    def __init__(self, simulation_only: bool = True,
                 ramp_up_ms: float   = DEFAULT_RAMP_UP_MS,
                 sustain_ms: float   = DEFAULT_SUSTAIN_MS,
                 ramp_down_ms: float = DEFAULT_RAMP_DOWN_MS):
        self.simulation_only = simulation_only
        self.ramp_up_ms   = ramp_up_ms
        self.sustain_ms   = sustain_ms
        self.ramp_down_ms = ramp_down_ms

        if not simulation_only:
            logger.warning("⚠  HARDWARE MODE ACTIVE — ensure clinical validation complete")

    def generate(self, estimate: ExpressionEstimate) -> Optional[StimulationProfile]:
        """Generate stimulation profile. Returns None for NEUTRAL/UNKNOWN."""
        muscle = self.MUSCLE_MAP.get(estimate.expression)
        if not muscle or estimate.expression == Expression.NEUTRAL:
            return None

        if estimate.confidence < 0.70:
            return None   # Below confidence threshold

        return StimulationProfile(
            timestamp=estimate.timestamp,
            enabled=True,
            simulation_only=self.simulation_only,
            target_muscle=muscle,
            ramp_up_ms=self.ramp_up_ms,
            sustain_ms=self.sustain_ms * estimate.intensity,   # Scale duration by intensity
            ramp_down_ms=self.ramp_down_ms,
            peak_intensity_norm=round(estimate.intensity, 3),
            # Hardware parameters: None until clinician-defined
            current_ma=None,
            pulse_width_us=None,
            frequency_hz=None,
        )


# ─────────────────────────────────────────────────────────────────────────────
# Complete Pipeline
# ─────────────────────────────────────────────────────────────────────────────

class SignalProcessingPipeline:
    """
    8-step signal processing pipeline for the OFNP.
    Steps 7 (safety) and 8 (logging) are injected as callbacks to keep
    concerns separated and ensure safety cannot be bypassed.
    """

    def __init__(self,
                 thresholds: Optional[ExpressionThresholds] = None,
                 simulation_only: bool = True,
                 power_line_hz: float = 50.0,
                 sample_rate_hz: float = 1000.0,
                 safety_callback=None,
                 logging_callback=None):
        self.emg_filter   = EMGFilter(power_line_hz, sample_rate_hz)
        self.extractor    = FeatureExtractor(sample_rate_hz)
        self.detector     = ExpressionDetector(thresholds)
        self.stim_gen     = StimulationProfileGenerator(simulation_only)
        self._safety_cb   = safety_callback
        self._logging_cb  = logging_callback
        self._tick        = 0
        self._latencies   = collections.deque(maxlen=1000)

        logger.info("[Pipeline] Initialized — simulation_only=%s", simulation_only)

    def process_sample(self, sample: RawSample) -> Optional[StimulationProfile]:
        """
        Process one raw EMG sample through the full pipeline.
        Returns StimulationProfile if expression detected and safety cleared.
        Returns None otherwise.
        """
        t_start = time.time()
        self._tick += 1

        # Step 2: Filter
        filtered = self.emg_filter.filter(sample)

        # Step 3: Feature extraction (returns None until window complete)
        features = self.extractor.push(filtered)
        if features is None:
            return None

        # Step 4-5: Detect expression + validate trigger
        estimate = self.detector.detect(features)

        # Log expression estimate
        if self._logging_cb:
            self._logging_cb("expression_estimate", {
                "expression": estimate.expression.value,
                "confidence": estimate.confidence,
                "intensity":  estimate.intensity,
                "rms_uv":     estimate.healthy_rms_uv,
            })

        if estimate.expression == Expression.NEUTRAL:
            return None

        # Step 6: Generate stimulation profile
        profile = self.stim_gen.generate(estimate)
        if profile is None:
            return None

        # Step 7: Safety verification — CANNOT be skipped
        if self._safety_cb:
            safe, reason = self._safety_cb(profile, filtered, features)
            if not safe:
                logger.warning("[Pipeline] Safety block: %s", reason)
                if self._logging_cb:
                    self._logging_cb("safety_block", {"reason": reason})
                return None

        # Step 8: Log final output
        total_latency = (time.time() - t_start) * 1000
        self._latencies.append(total_latency)

        if self._logging_cb:
            self._logging_cb("stimulation_command", {
                **profile.to_dict(),
                "pipeline_latency_ms": round(total_latency, 2),
            })

        return profile

    @property
    def mean_latency_ms(self) -> float:
        return float(np.mean(self._latencies)) if self._latencies else 0.0

    @property
    def tick_count(self) -> int:
        return self._tick
